"""Add foreign key to tasks

Revision ID: db88119d3f1d
Revises: deaeed69efe1
Create Date: 2024-07-25 12:38:42.583206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db88119d3f1d'
down_revision = 'deaeed69efe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
